// NOTE: This file was first generated by wayland-scanner 1.20.0 from the
// Wayland XML protocol and subsequently converted with rust-bindgen. For
// the implementation of inline static Wayland functions and interfaces,
// search for "Static inline symbols".

use crate::{
	NULL_VOID, //
	c_str,
};

pub use super::core::*;

pub const WL_DISPLAY_SYNC: u32 = 0;
pub const WL_DISPLAY_GET_REGISTRY: u32 = 1;
pub const WL_DISPLAY_ERROR_SINCE_VERSION: u32 = 1;
pub const WL_DISPLAY_DELETE_ID_SINCE_VERSION: u32 = 1;
pub const WL_DISPLAY_SYNC_SINCE_VERSION: u32 = 1;
pub const WL_DISPLAY_GET_REGISTRY_SINCE_VERSION: u32 = 1;

pub const WL_REGISTRY_BIND: u32 = 0;
pub const WL_REGISTRY_GLOBAL_SINCE_VERSION: u32 = 1;
pub const WL_REGISTRY_GLOBAL_REMOVE_SINCE_VERSION: u32 = 1;
pub const WL_REGISTRY_BIND_SINCE_VERSION: u32 = 1;

pub const WL_CALLBACK_DONE_SINCE_VERSION: u32 = 1;

pub const WL_COMPOSITOR_CREATE_SURFACE: u32 = 0;
pub const WL_COMPOSITOR_CREATE_REGION: u32 = 1;
pub const WL_COMPOSITOR_CREATE_SURFACE_SINCE_VERSION: u32 = 1;
pub const WL_COMPOSITOR_CREATE_REGION_SINCE_VERSION: u32 = 1;

pub const WL_SHM_POOL_CREATE_BUFFER: u32 = 0;
pub const WL_SHM_POOL_DESTROY: u32 = 1;
pub const WL_SHM_POOL_RESIZE: u32 = 2;
pub const WL_SHM_POOL_CREATE_BUFFER_SINCE_VERSION: u32 = 1;
pub const WL_SHM_POOL_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_SHM_POOL_RESIZE_SINCE_VERSION: u32 = 1;

pub const WL_SHM_CREATE_POOL: u32 = 0;
pub const WL_SHM_RELEASE: u32 = 1;
pub const WL_SHM_FORMAT_SINCE_VERSION: u32 = 1;
pub const WL_SHM_CREATE_POOL_SINCE_VERSION: u32 = 1;
pub const WL_SHM_RELEASE_SINCE_VERSION: u32 = 2;

pub const WL_BUFFER_DESTROY: u32 = 0;
pub const WL_BUFFER_RELEASE_SINCE_VERSION: u32 = 1;
pub const WL_BUFFER_DESTROY_SINCE_VERSION: u32 = 1;

pub const WL_DATA_OFFER_ACCEPT: u32 = 0;
pub const WL_DATA_OFFER_RECEIVE: u32 = 1;
pub const WL_DATA_OFFER_DESTROY: u32 = 2;
pub const WL_DATA_OFFER_FINISH: u32 = 3;
pub const WL_DATA_OFFER_SET_ACTIONS: u32 = 4;
pub const WL_DATA_OFFER_OFFER_SINCE_VERSION: u32 = 1;
pub const WL_DATA_OFFER_SOURCE_ACTIONS_SINCE_VERSION: u32 = 3;
pub const WL_DATA_OFFER_ACTION_SINCE_VERSION: u32 = 3;
pub const WL_DATA_OFFER_ACCEPT_SINCE_VERSION: u32 = 1;
pub const WL_DATA_OFFER_RECEIVE_SINCE_VERSION: u32 = 1;
pub const WL_DATA_OFFER_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_DATA_OFFER_FINISH_SINCE_VERSION: u32 = 3;
pub const WL_DATA_OFFER_SET_ACTIONS_SINCE_VERSION: u32 = 3;

pub const WL_DATA_SOURCE_OFFER: u32 = 0;
pub const WL_DATA_SOURCE_DESTROY: u32 = 1;
pub const WL_DATA_SOURCE_SET_ACTIONS: u32 = 2;
pub const WL_DATA_SOURCE_TARGET_SINCE_VERSION: u32 = 1;
pub const WL_DATA_SOURCE_SEND_SINCE_VERSION: u32 = 1;
pub const WL_DATA_SOURCE_CANCELLED_SINCE_VERSION: u32 = 1;
pub const WL_DATA_SOURCE_DND_DROP_PERFORMED_SINCE_VERSION: u32 = 3;
pub const WL_DATA_SOURCE_DND_FINISHED_SINCE_VERSION: u32 = 3;
pub const WL_DATA_SOURCE_ACTION_SINCE_VERSION: u32 = 3;
pub const WL_DATA_SOURCE_OFFER_SINCE_VERSION: u32 = 1;
pub const WL_DATA_SOURCE_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_DATA_SOURCE_SET_ACTIONS_SINCE_VERSION: u32 = 3;

pub const WL_DATA_DEVICE_START_DRAG: u32 = 0;
pub const WL_DATA_DEVICE_SET_SELECTION: u32 = 1;
pub const WL_DATA_DEVICE_RELEASE: u32 = 2;
pub const WL_DATA_DEVICE_DATA_OFFER_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_ENTER_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_LEAVE_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_MOTION_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_DROP_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_SELECTION_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_START_DRAG_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_SET_SELECTION_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_RELEASE_SINCE_VERSION: u32 = 2;

pub const WL_DATA_DEVICE_MANAGER_CREATE_DATA_SOURCE: u32 = 0;
pub const WL_DATA_DEVICE_MANAGER_GET_DATA_DEVICE: u32 = 1;
pub const WL_DATA_DEVICE_MANAGER_CREATE_DATA_SOURCE_SINCE_VERSION: u32 = 1;
pub const WL_DATA_DEVICE_MANAGER_GET_DATA_DEVICE_SINCE_VERSION: u32 = 1;

pub const WL_SHELL_GET_SHELL_SURFACE: u32 = 0;
pub const WL_SHELL_GET_SHELL_SURFACE_SINCE_VERSION: u32 = 1;

pub const WL_SHELL_SURFACE_PONG: u32 = 0;
pub const WL_SHELL_SURFACE_MOVE: u32 = 1;
pub const WL_SHELL_SURFACE_RESIZE: u32 = 2;
pub const WL_SHELL_SURFACE_SET_TOPLEVEL: u32 = 3;
pub const WL_SHELL_SURFACE_SET_TRANSIENT: u32 = 4;
pub const WL_SHELL_SURFACE_SET_FULLSCREEN: u32 = 5;
pub const WL_SHELL_SURFACE_SET_POPUP: u32 = 6;
pub const WL_SHELL_SURFACE_SET_MAXIMIZED: u32 = 7;
pub const WL_SHELL_SURFACE_SET_TITLE: u32 = 8;
pub const WL_SHELL_SURFACE_SET_CLASS: u32 = 9;
pub const WL_SHELL_SURFACE_PING_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_CONFIGURE_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_POPUP_DONE_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_PONG_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_MOVE_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_RESIZE_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_TOPLEVEL_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_TRANSIENT_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_FULLSCREEN_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_POPUP_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_MAXIMIZED_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_TITLE_SINCE_VERSION: u32 = 1;
pub const WL_SHELL_SURFACE_SET_CLASS_SINCE_VERSION: u32 = 1;

pub const WL_SURFACE_DESTROY: u32 = 0;
pub const WL_SURFACE_ATTACH: u32 = 1;
pub const WL_SURFACE_DAMAGE: u32 = 2;
pub const WL_SURFACE_FRAME: u32 = 3;
pub const WL_SURFACE_SET_OPAQUE_REGION: u32 = 4;
pub const WL_SURFACE_SET_INPUT_REGION: u32 = 5;
pub const WL_SURFACE_COMMIT: u32 = 6;
pub const WL_SURFACE_SET_BUFFER_TRANSFORM: u32 = 7;
pub const WL_SURFACE_SET_BUFFER_SCALE: u32 = 8;
pub const WL_SURFACE_DAMAGE_BUFFER: u32 = 9;
pub const WL_SURFACE_OFFSET: u32 = 10;
pub const WL_SURFACE_ENTER_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_LEAVE_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_PREFERRED_BUFFER_SCALE_SINCE_VERSION: u32 = 6;
pub const WL_SURFACE_PREFERRED_BUFFER_TRANSFORM_SINCE_VERSION: u32 = 6;
pub const WL_SURFACE_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_ATTACH_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_DAMAGE_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_FRAME_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_SET_OPAQUE_REGION_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_SET_INPUT_REGION_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_COMMIT_SINCE_VERSION: u32 = 1;
pub const WL_SURFACE_SET_BUFFER_TRANSFORM_SINCE_VERSION: u32 = 2;
pub const WL_SURFACE_SET_BUFFER_SCALE_SINCE_VERSION: u32 = 3;
pub const WL_SURFACE_DAMAGE_BUFFER_SINCE_VERSION: u32 = 4;
pub const WL_SURFACE_OFFSET_SINCE_VERSION: u32 = 5;

pub const WL_SEAT_GET_POINTER: u32 = 0;
pub const WL_SEAT_GET_KEYBOARD: u32 = 1;
pub const WL_SEAT_GET_TOUCH: u32 = 2;
pub const WL_SEAT_RELEASE: u32 = 3;
pub const WL_SEAT_CAPABILITIES_SINCE_VERSION: u32 = 1;
pub const WL_SEAT_NAME_SINCE_VERSION: u32 = 2;
pub const WL_SEAT_GET_POINTER_SINCE_VERSION: u32 = 1;
pub const WL_SEAT_GET_KEYBOARD_SINCE_VERSION: u32 = 1;
pub const WL_SEAT_GET_TOUCH_SINCE_VERSION: u32 = 1;
pub const WL_SEAT_RELEASE_SINCE_VERSION: u32 = 5;

pub const WL_POINTER_AXIS_SOURCE_WHEEL_TILT_SINCE_VERSION: u32 = 6;
pub const WL_POINTER_SET_CURSOR: u32 = 0;
pub const WL_POINTER_RELEASE: u32 = 1;
pub const WL_POINTER_ENTER_SINCE_VERSION: u32 = 1;
pub const WL_POINTER_LEAVE_SINCE_VERSION: u32 = 1;
pub const WL_POINTER_MOTION_SINCE_VERSION: u32 = 1;
pub const WL_POINTER_BUTTON_SINCE_VERSION: u32 = 1;
pub const WL_POINTER_AXIS_SINCE_VERSION: u32 = 1;
pub const WL_POINTER_FRAME_SINCE_VERSION: u32 = 5;
pub const WL_POINTER_AXIS_SOURCE_SINCE_VERSION: u32 = 5;
pub const WL_POINTER_AXIS_STOP_SINCE_VERSION: u32 = 5;
pub const WL_POINTER_AXIS_DISCRETE_SINCE_VERSION: u32 = 5;
pub const WL_POINTER_AXIS_VALUE120_SINCE_VERSION: u32 = 8;
pub const WL_POINTER_AXIS_RELATIVE_DIRECTION_SINCE_VERSION: u32 = 9;
pub const WL_POINTER_SET_CURSOR_SINCE_VERSION: u32 = 1;
pub const WL_POINTER_RELEASE_SINCE_VERSION: u32 = 3;

pub const WL_KEYBOARD_KEY_STATE_REPEATED_SINCE_VERSION: u32 = 10;
pub const WL_KEYBOARD_RELEASE: u32 = 0;
pub const WL_KEYBOARD_KEYMAP_SINCE_VERSION: u32 = 1;
pub const WL_KEYBOARD_ENTER_SINCE_VERSION: u32 = 1;
pub const WL_KEYBOARD_LEAVE_SINCE_VERSION: u32 = 1;
pub const WL_KEYBOARD_KEY_SINCE_VERSION: u32 = 1;
pub const WL_KEYBOARD_MODIFIERS_SINCE_VERSION: u32 = 1;
pub const WL_KEYBOARD_REPEAT_INFO_SINCE_VERSION: u32 = 4;
pub const WL_KEYBOARD_RELEASE_SINCE_VERSION: u32 = 3;

pub const WL_TOUCH_RELEASE: u32 = 0;
pub const WL_TOUCH_DOWN_SINCE_VERSION: u32 = 1;
pub const WL_TOUCH_UP_SINCE_VERSION: u32 = 1;
pub const WL_TOUCH_MOTION_SINCE_VERSION: u32 = 1;
pub const WL_TOUCH_FRAME_SINCE_VERSION: u32 = 1;
pub const WL_TOUCH_CANCEL_SINCE_VERSION: u32 = 1;
pub const WL_TOUCH_SHAPE_SINCE_VERSION: u32 = 6;
pub const WL_TOUCH_ORIENTATION_SINCE_VERSION: u32 = 6;
pub const WL_TOUCH_RELEASE_SINCE_VERSION: u32 = 3;

pub const WL_OUTPUT_RELEASE: u32 = 0;
pub const WL_OUTPUT_GEOMETRY_SINCE_VERSION: u32 = 1;
pub const WL_OUTPUT_MODE_SINCE_VERSION: u32 = 1;
pub const WL_OUTPUT_DONE_SINCE_VERSION: u32 = 2;
pub const WL_OUTPUT_SCALE_SINCE_VERSION: u32 = 2;
pub const WL_OUTPUT_NAME_SINCE_VERSION: u32 = 4;
pub const WL_OUTPUT_DESCRIPTION_SINCE_VERSION: u32 = 4;
pub const WL_OUTPUT_RELEASE_SINCE_VERSION: u32 = 3;

pub const WL_REGION_DESTROY: u32 = 0;
pub const WL_REGION_ADD: u32 = 1;
pub const WL_REGION_SUBTRACT: u32 = 2;
pub const WL_REGION_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_REGION_ADD_SINCE_VERSION: u32 = 1;
pub const WL_REGION_SUBTRACT_SINCE_VERSION: u32 = 1;

pub const WL_SUBCOMPOSITOR_DESTROY: u32 = 0;
pub const WL_SUBCOMPOSITOR_GET_SUBSURFACE: u32 = 1;
pub const WL_SUBCOMPOSITOR_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_SUBCOMPOSITOR_GET_SUBSURFACE_SINCE_VERSION: u32 = 1;

pub const WL_SUBSURFACE_DESTROY: u32 = 0;
pub const WL_SUBSURFACE_SET_POSITION: u32 = 1;
pub const WL_SUBSURFACE_PLACE_ABOVE: u32 = 2;
pub const WL_SUBSURFACE_PLACE_BELOW: u32 = 3;
pub const WL_SUBSURFACE_SET_SYNC: u32 = 4;
pub const WL_SUBSURFACE_SET_DESYNC: u32 = 5;
pub const WL_SUBSURFACE_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_SUBSURFACE_SET_POSITION_SINCE_VERSION: u32 = 1;
pub const WL_SUBSURFACE_PLACE_ABOVE_SINCE_VERSION: u32 = 1;
pub const WL_SUBSURFACE_PLACE_BELOW_SINCE_VERSION: u32 = 1;
pub const WL_SUBSURFACE_SET_SYNC_SINCE_VERSION: u32 = 1;
pub const WL_SUBSURFACE_SET_DESYNC_SINCE_VERSION: u32 = 1;

pub const WL_FIXES_DESTROY: u32 = 0;
pub const WL_FIXES_DESTROY_REGISTRY: u32 = 1;
pub const WL_FIXES_DESTROY_SINCE_VERSION: u32 = 1;
pub const WL_FIXES_DESTROY_REGISTRY_SINCE_VERSION: u32 = 1;

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_buffer {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_callback {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_compositor {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_data_device {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_data_device_manager {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_data_offer {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_data_source {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_fixes {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_keyboard {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_output {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_pointer {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_region {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_registry {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_seat {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_shell {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_shell_surface {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_shm {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_shm_pool {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_subcompositor {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_subsurface {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_surface {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct wl_touch {
	_unused: [u8; 0],
}

pub type wl_display_error = u32;
pub const WL_DISPLAY_ERROR_INVALID_OBJECT: wl_display_error = 0;
pub const WL_DISPLAY_ERROR_INVALID_METHOD: wl_display_error = 1;
pub const WL_DISPLAY_ERROR_NO_MEMORY: wl_display_error = 2;
pub const WL_DISPLAY_ERROR_IMPLEMENTATION: wl_display_error = 3;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_display_listener {
	pub error: unsafe extern "C" fn(data: *mut (), wl_display: *mut wl_display, object_id: *mut (), code: u32, message: *const i8),

	pub delete_id: unsafe extern "C" fn(data: *mut (), wl_display: *mut wl_display, id: u32),
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_registry_listener {
	pub global: unsafe extern "C" fn(data: *mut (), wl_registry: *mut wl_registry, name: u32, interface: *const i8, version: u32),

	pub global_remove: unsafe extern "C" fn(data: *mut (), wl_registry: *mut wl_registry, name: u32),
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_callback_listener {
	pub done: unsafe extern "C" fn(data: *mut (), wl_callback: *mut wl_callback, callback_data: u32),
}

pub type wl_shm_error = u32;
pub const WL_SHM_ERROR_INVALID_FORMAT: wl_shm_error = 0;
pub const WL_SHM_ERROR_INVALID_STRIDE: wl_shm_error = 1;
pub const WL_SHM_ERROR_INVALID_FD: wl_shm_error = 2;

pub type wl_shm_format = u32;
pub const WL_SHM_FORMAT_ARGB8888: wl_shm_format = 0;
pub const WL_SHM_FORMAT_XRGB8888: wl_shm_format = 1;
pub const WL_SHM_FORMAT_C8: wl_shm_format = 538982467;
pub const WL_SHM_FORMAT_RGB332: wl_shm_format = 943867730;
pub const WL_SHM_FORMAT_BGR233: wl_shm_format = 944916290;
pub const WL_SHM_FORMAT_XRGB4444: wl_shm_format = 842093144;
pub const WL_SHM_FORMAT_XBGR4444: wl_shm_format = 842089048;
pub const WL_SHM_FORMAT_RGBX4444: wl_shm_format = 842094674;
pub const WL_SHM_FORMAT_BGRX4444: wl_shm_format = 842094658;
pub const WL_SHM_FORMAT_ARGB4444: wl_shm_format = 842093121;
pub const WL_SHM_FORMAT_ABGR4444: wl_shm_format = 842089025;
pub const WL_SHM_FORMAT_RGBA4444: wl_shm_format = 842088786;
pub const WL_SHM_FORMAT_BGRA4444: wl_shm_format = 842088770;
pub const WL_SHM_FORMAT_XRGB1555: wl_shm_format = 892424792;
pub const WL_SHM_FORMAT_XBGR1555: wl_shm_format = 892420696;
pub const WL_SHM_FORMAT_RGBX5551: wl_shm_format = 892426322;
pub const WL_SHM_FORMAT_BGRX5551: wl_shm_format = 892426306;
pub const WL_SHM_FORMAT_ARGB1555: wl_shm_format = 892424769;
pub const WL_SHM_FORMAT_ABGR1555: wl_shm_format = 892420673;
pub const WL_SHM_FORMAT_RGBA5551: wl_shm_format = 892420434;
pub const WL_SHM_FORMAT_BGRA5551: wl_shm_format = 892420418;
pub const WL_SHM_FORMAT_RGB565: wl_shm_format = 909199186;
pub const WL_SHM_FORMAT_BGR565: wl_shm_format = 909199170;
pub const WL_SHM_FORMAT_RGB888: wl_shm_format = 875710290;
pub const WL_SHM_FORMAT_BGR888: wl_shm_format = 875710274;
pub const WL_SHM_FORMAT_XBGR8888: wl_shm_format = 875709016;
pub const WL_SHM_FORMAT_RGBX8888: wl_shm_format = 875714642;
pub const WL_SHM_FORMAT_BGRX8888: wl_shm_format = 875714626;
pub const WL_SHM_FORMAT_ABGR8888: wl_shm_format = 875708993;
pub const WL_SHM_FORMAT_RGBA8888: wl_shm_format = 875708754;
pub const WL_SHM_FORMAT_BGRA8888: wl_shm_format = 875708738;
pub const WL_SHM_FORMAT_XRGB2101010: wl_shm_format = 808669784;
pub const WL_SHM_FORMAT_XBGR2101010: wl_shm_format = 808665688;
pub const WL_SHM_FORMAT_RGBX1010102: wl_shm_format = 808671314;
pub const WL_SHM_FORMAT_BGRX1010102: wl_shm_format = 808671298;
pub const WL_SHM_FORMAT_ARGB2101010: wl_shm_format = 808669761;
pub const WL_SHM_FORMAT_ABGR2101010: wl_shm_format = 808665665;
pub const WL_SHM_FORMAT_RGBA1010102: wl_shm_format = 808665426;
pub const WL_SHM_FORMAT_BGRA1010102: wl_shm_format = 808665410;
pub const WL_SHM_FORMAT_YUYV: wl_shm_format = 1448695129;
pub const WL_SHM_FORMAT_YVYU: wl_shm_format = 1431918169;
pub const WL_SHM_FORMAT_UYVY: wl_shm_format = 1498831189;
pub const WL_SHM_FORMAT_VYUY: wl_shm_format = 1498765654;
pub const WL_SHM_FORMAT_AYUV: wl_shm_format = 1448433985;
pub const WL_SHM_FORMAT_NV12: wl_shm_format = 842094158;
pub const WL_SHM_FORMAT_NV21: wl_shm_format = 825382478;
pub const WL_SHM_FORMAT_NV16: wl_shm_format = 909203022;
pub const WL_SHM_FORMAT_NV61: wl_shm_format = 825644622;
pub const WL_SHM_FORMAT_YUV410: wl_shm_format = 961959257;
pub const WL_SHM_FORMAT_YVU410: wl_shm_format = 961893977;
pub const WL_SHM_FORMAT_YUV411: wl_shm_format = 825316697;
pub const WL_SHM_FORMAT_YVU411: wl_shm_format = 825316953;
pub const WL_SHM_FORMAT_YUV420: wl_shm_format = 842093913;
pub const WL_SHM_FORMAT_YVU420: wl_shm_format = 842094169;
pub const WL_SHM_FORMAT_YUV422: wl_shm_format = 909202777;
pub const WL_SHM_FORMAT_YVU422: wl_shm_format = 909203033;
pub const WL_SHM_FORMAT_YUV444: wl_shm_format = 875713881;
pub const WL_SHM_FORMAT_YVU444: wl_shm_format = 875714137;
pub const WL_SHM_FORMAT_R8: wl_shm_format = 538982482;
pub const WL_SHM_FORMAT_R16: wl_shm_format = 540422482;
pub const WL_SHM_FORMAT_RG88: wl_shm_format = 943212370;
pub const WL_SHM_FORMAT_GR88: wl_shm_format = 943215175;
pub const WL_SHM_FORMAT_RG1616: wl_shm_format = 842221394;
pub const WL_SHM_FORMAT_GR1616: wl_shm_format = 842224199;
pub const WL_SHM_FORMAT_XRGB16161616F: wl_shm_format = 1211388504;
pub const WL_SHM_FORMAT_XBGR16161616F: wl_shm_format = 1211384408;
pub const WL_SHM_FORMAT_ARGB16161616F: wl_shm_format = 1211388481;
pub const WL_SHM_FORMAT_ABGR16161616F: wl_shm_format = 1211384385;
pub const WL_SHM_FORMAT_XYUV8888: wl_shm_format = 1448434008;
pub const WL_SHM_FORMAT_VUY888: wl_shm_format = 875713878;
pub const WL_SHM_FORMAT_VUY101010: wl_shm_format = 808670550;
pub const WL_SHM_FORMAT_Y210: wl_shm_format = 808530521;
pub const WL_SHM_FORMAT_Y212: wl_shm_format = 842084953;
pub const WL_SHM_FORMAT_Y216: wl_shm_format = 909193817;
pub const WL_SHM_FORMAT_Y410: wl_shm_format = 808531033;
pub const WL_SHM_FORMAT_Y412: wl_shm_format = 842085465;
pub const WL_SHM_FORMAT_Y416: wl_shm_format = 909194329;
pub const WL_SHM_FORMAT_XVYU2101010: wl_shm_format = 808670808;
pub const WL_SHM_FORMAT_XVYU12_16161616: wl_shm_format = 909334104;
pub const WL_SHM_FORMAT_XVYU16161616: wl_shm_format = 942954072;
pub const WL_SHM_FORMAT_Y0L0: wl_shm_format = 810299481;
pub const WL_SHM_FORMAT_X0L0: wl_shm_format = 810299480;
pub const WL_SHM_FORMAT_Y0L2: wl_shm_format = 843853913;
pub const WL_SHM_FORMAT_X0L2: wl_shm_format = 843853912;
pub const WL_SHM_FORMAT_YUV420_8BIT: wl_shm_format = 942691673;
pub const WL_SHM_FORMAT_YUV420_10BIT: wl_shm_format = 808539481;
pub const WL_SHM_FORMAT_XRGB8888_A8: wl_shm_format = 943805016;
pub const WL_SHM_FORMAT_XBGR8888_A8: wl_shm_format = 943800920;
pub const WL_SHM_FORMAT_RGBX8888_A8: wl_shm_format = 943806546;
pub const WL_SHM_FORMAT_BGRX8888_A8: wl_shm_format = 943806530;
pub const WL_SHM_FORMAT_RGB888_A8: wl_shm_format = 943798354;
pub const WL_SHM_FORMAT_BGR888_A8: wl_shm_format = 943798338;
pub const WL_SHM_FORMAT_RGB565_A8: wl_shm_format = 943797586;
pub const WL_SHM_FORMAT_BGR565_A8: wl_shm_format = 943797570;
pub const WL_SHM_FORMAT_NV24: wl_shm_format = 875714126;
pub const WL_SHM_FORMAT_NV42: wl_shm_format = 842290766;
pub const WL_SHM_FORMAT_P210: wl_shm_format = 808530512;
pub const WL_SHM_FORMAT_P010: wl_shm_format = 808530000;
pub const WL_SHM_FORMAT_P012: wl_shm_format = 842084432;
pub const WL_SHM_FORMAT_P016: wl_shm_format = 909193296;
pub const WL_SHM_FORMAT_AXBXGXRX106106106106: wl_shm_format = 808534593;
pub const WL_SHM_FORMAT_NV15: wl_shm_format = 892425806;
pub const WL_SHM_FORMAT_Q410: wl_shm_format = 808531025;
pub const WL_SHM_FORMAT_Q401: wl_shm_format = 825242705;
pub const WL_SHM_FORMAT_XRGB16161616: wl_shm_format = 942953048;
pub const WL_SHM_FORMAT_XBGR16161616: wl_shm_format = 942948952;
pub const WL_SHM_FORMAT_ARGB16161616: wl_shm_format = 942953025;
pub const WL_SHM_FORMAT_ABGR16161616: wl_shm_format = 942948929;
pub const WL_SHM_FORMAT_C1: wl_shm_format = 538980675;
pub const WL_SHM_FORMAT_C2: wl_shm_format = 538980931;
pub const WL_SHM_FORMAT_C4: wl_shm_format = 538981443;
pub const WL_SHM_FORMAT_D1: wl_shm_format = 538980676;
pub const WL_SHM_FORMAT_D2: wl_shm_format = 538980932;
pub const WL_SHM_FORMAT_D4: wl_shm_format = 538981444;
pub const WL_SHM_FORMAT_D8: wl_shm_format = 538982468;
pub const WL_SHM_FORMAT_R1: wl_shm_format = 538980690;
pub const WL_SHM_FORMAT_R2: wl_shm_format = 538980946;
pub const WL_SHM_FORMAT_R4: wl_shm_format = 538981458;
pub const WL_SHM_FORMAT_R10: wl_shm_format = 540029266;
pub const WL_SHM_FORMAT_R12: wl_shm_format = 540160338;
pub const WL_SHM_FORMAT_AVUY8888: wl_shm_format = 1498764865;
pub const WL_SHM_FORMAT_XVUY8888: wl_shm_format = 1498764888;
pub const WL_SHM_FORMAT_P030: wl_shm_format = 808661072;
pub const WL_SHM_FORMAT_RGB161616: wl_shm_format = 942950226;
pub const WL_SHM_FORMAT_BGR161616: wl_shm_format = 942950210;
pub const WL_SHM_FORMAT_R16F: wl_shm_format = 1210064978;
pub const WL_SHM_FORMAT_GR1616F: wl_shm_format = 1210077767;
pub const WL_SHM_FORMAT_BGR161616F: wl_shm_format = 1213351746;
pub const WL_SHM_FORMAT_R32F: wl_shm_format = 1176510546;
pub const WL_SHM_FORMAT_GR3232F: wl_shm_format = 1176523335;
pub const WL_SHM_FORMAT_BGR323232F: wl_shm_format = 1179797314;
pub const WL_SHM_FORMAT_ABGR32323232F: wl_shm_format = 1178092097;
pub const WL_SHM_FORMAT_NV20: wl_shm_format = 808605262;
pub const WL_SHM_FORMAT_NV30: wl_shm_format = 808670798;
pub const WL_SHM_FORMAT_S010: wl_shm_format = 808530003;
pub const WL_SHM_FORMAT_S210: wl_shm_format = 808530515;
pub const WL_SHM_FORMAT_S410: wl_shm_format = 808531027;
pub const WL_SHM_FORMAT_S012: wl_shm_format = 842084435;
pub const WL_SHM_FORMAT_S212: wl_shm_format = 842084947;
pub const WL_SHM_FORMAT_S412: wl_shm_format = 842085459;
pub const WL_SHM_FORMAT_S016: wl_shm_format = 909193299;
pub const WL_SHM_FORMAT_S216: wl_shm_format = 909193811;
pub const WL_SHM_FORMAT_S416: wl_shm_format = 909194323;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_shm_listener {
	pub format: unsafe extern "C" fn(data: *mut (), wl_shm: *mut wl_shm, format: u32),
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_buffer_listener {
	pub release: unsafe extern "C" fn(data: *mut (), wl_buffer: *mut wl_buffer),
}

pub type wl_data_offer_error = u32;
pub const WL_DATA_OFFER_ERROR_INVALID_FINISH: wl_data_offer_error = 0;
pub const WL_DATA_OFFER_ERROR_INVALID_ACTION_MASK: wl_data_offer_error = 1;
pub const WL_DATA_OFFER_ERROR_INVALID_ACTION: wl_data_offer_error = 2;
pub const WL_DATA_OFFER_ERROR_INVALID_OFFER: wl_data_offer_error = 3;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_data_offer_listener {
	pub offer: unsafe extern "C" fn(data: *mut (), wl_data_offer: *mut wl_data_offer, mime_type: *const i8),

	pub source_actions: unsafe extern "C" fn(data: *mut (), wl_data_offer: *mut wl_data_offer, source_actions: u32),

	pub action: unsafe extern "C" fn(data: *mut (), wl_data_offer: *mut wl_data_offer, dnd_action: u32),
}

pub type wl_data_source_error = u32;
pub const WL_DATA_SOURCE_ERROR_INVALID_ACTION_MASK: wl_data_source_error = 0;
pub const WL_DATA_SOURCE_ERROR_INVALID_SOURCE: wl_data_source_error = 1;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_data_source_listener {
	pub target: unsafe extern "C" fn(data: *mut (), wl_data_source: *mut wl_data_source, mime_type: *const i8),

	pub send: unsafe extern "C" fn(data: *mut (), wl_data_source: *mut wl_data_source, mime_type: *const i8, fd: i32),

	pub cancelled: unsafe extern "C" fn(data: *mut (), wl_data_source: *mut wl_data_source),

	pub dnd_drop_performed: unsafe extern "C" fn(data: *mut (), wl_data_source: *mut wl_data_source),

	pub dnd_finished: unsafe extern "C" fn(data: *mut (), wl_data_source: *mut wl_data_source),

	pub action: unsafe extern "C" fn(data: *mut (), wl_data_source: *mut wl_data_source, dnd_action: u32),
}

pub type wl_data_device_error = u32;
pub const WL_DATA_DEVICE_ERROR_ROLE: wl_data_device_error = 0;
pub const WL_DATA_DEVICE_ERROR_USED_SOURCE: wl_data_device_error = 1;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_data_device_listener {
	pub data_offer: unsafe extern "C" fn(data: *mut (), wl_data_device: *mut wl_data_device, id: *mut wl_data_offer),

	pub enter: unsafe extern "C" fn(data: *mut (), wl_data_device: *mut wl_data_device, serial: u32, surface: *mut wl_surface, x: wl_fixed_t, y: wl_fixed_t, id: *mut wl_data_offer),

	pub leave: unsafe extern "C" fn(data: *mut (), wl_data_device: *mut wl_data_device),

	pub motion: unsafe extern "C" fn(data: *mut (), wl_data_device: *mut wl_data_device, time: u32, x: wl_fixed_t, y: wl_fixed_t),

	pub drop: unsafe extern "C" fn(data: *mut (), wl_data_device: *mut wl_data_device),

	pub selection: unsafe extern "C" fn(data: *mut (), wl_data_device: *mut wl_data_device, id: *mut wl_data_offer),
}

pub type wl_data_device_manager_dnd_action = u32;
pub const WL_DATA_DEVICE_MANAGER_DND_ACTION_NONE: wl_data_device_manager_dnd_action = 0;
pub const WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY: wl_data_device_manager_dnd_action = 1;
pub const WL_DATA_DEVICE_MANAGER_DND_ACTION_MOVE: wl_data_device_manager_dnd_action = 2;
pub const WL_DATA_DEVICE_MANAGER_DND_ACTION_ASK: wl_data_device_manager_dnd_action = 4;

pub type wl_shell_error = u32;
pub const WL_SHELL_ERROR_ROLE: wl_shell_error = 0;

pub type wl_shell_surface_resize = u32;
pub const WL_SHELL_SURFACE_RESIZE_NONE: wl_shell_surface_resize = 0;
pub const WL_SHELL_SURFACE_RESIZE_TOP: wl_shell_surface_resize = 1;
pub const WL_SHELL_SURFACE_RESIZE_BOTTOM: wl_shell_surface_resize = 2;
pub const WL_SHELL_SURFACE_RESIZE_LEFT: wl_shell_surface_resize = 4;
pub const WL_SHELL_SURFACE_RESIZE_TOP_LEFT: wl_shell_surface_resize = 5;
pub const WL_SHELL_SURFACE_RESIZE_BOTTOM_LEFT: wl_shell_surface_resize = 6;
pub const WL_SHELL_SURFACE_RESIZE_RIGHT: wl_shell_surface_resize = 8;
pub const WL_SHELL_SURFACE_RESIZE_TOP_RIGHT: wl_shell_surface_resize = 9;
pub const WL_SHELL_SURFACE_RESIZE_BOTTOM_RIGHT: wl_shell_surface_resize = 10;

pub type wl_shell_surface_transient = u32;
pub const WL_SHELL_SURFACE_TRANSIENT_INACTIVE: wl_shell_surface_transient = 1;

pub type wl_shell_surface_fullscreen_method = u32;
pub const WL_SHELL_SURFACE_FULLSCREEN_METHOD_DEFAULT: wl_shell_surface_fullscreen_method = 0;
pub const WL_SHELL_SURFACE_FULLSCREEN_METHOD_SCALE: wl_shell_surface_fullscreen_method = 1;
pub const WL_SHELL_SURFACE_FULLSCREEN_METHOD_DRIVER: wl_shell_surface_fullscreen_method = 2;
pub const WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL: wl_shell_surface_fullscreen_method = 3;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_shell_surface_listener {
	pub ping: unsafe extern "C" fn(data: *mut (), wl_shell_surface: *mut wl_shell_surface, serial: u32),

	pub configure: unsafe extern "C" fn(data: *mut (), wl_shell_surface: *mut wl_shell_surface, edges: u32, width: i32, height: i32),

	pub popup_done: unsafe extern "C" fn(data: *mut (), wl_shell_surface: *mut wl_shell_surface),
}

pub type wl_surface_error = u32;
pub const WL_SURFACE_ERROR_INVALID_SCALE: wl_surface_error = 0;
pub const WL_SURFACE_ERROR_INVALID_TRANSFORM: wl_surface_error = 1;
pub const WL_SURFACE_ERROR_INVALID_SIZE: wl_surface_error = 2;
pub const WL_SURFACE_ERROR_INVALID_OFFSET: wl_surface_error = 3;
pub const WL_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT: wl_surface_error = 4;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_surface_listener {
	pub enter: unsafe extern "C" fn(data: *mut (), wl_surface: *mut wl_surface, output: *mut wl_output),

	pub leave: unsafe extern "C" fn(data: *mut (), wl_surface: *mut wl_surface, output: *mut wl_output),

	pub preferred_buffer_scale: unsafe extern "C" fn(data: *mut (), wl_surface: *mut wl_surface, factor: i32),

	pub preferred_buffer_transform: unsafe extern "C" fn(data: *mut (), wl_surface: *mut wl_surface, transform: u32),
}

pub type wl_seat_capability = u32;
pub const WL_SEAT_CAPABILITY_POINTER: wl_seat_capability = 1;
pub const WL_SEAT_CAPABILITY_KEYBOARD: wl_seat_capability = 2;
pub const WL_SEAT_CAPABILITY_TOUCH: wl_seat_capability = 4;

pub type wl_seat_error = u32;
pub const WL_SEAT_ERROR_MISSING_CAPABILITY: wl_seat_error = 0;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_seat_listener {
	pub capabilities: unsafe extern "C" fn(data: *mut (), wl_seat: *mut wl_seat, capabilities: u32),

	pub name: unsafe extern "C" fn(data: *mut (), wl_seat: *mut wl_seat, name: *const i8),
}

pub type wl_pointer_error = u32;
pub const WL_POINTER_ERROR_ROLE: wl_pointer_error = 0;

pub type wl_pointer_button_state = u32;
pub const WL_POINTER_BUTTON_STATE_RELEASED: wl_pointer_button_state = 0;
pub const WL_POINTER_BUTTON_STATE_PRESSED: wl_pointer_button_state = 1;

pub type wl_pointer_axis = u32;
pub const WL_POINTER_AXIS_VERTICAL_SCROLL: wl_pointer_axis = 0;
pub const WL_POINTER_AXIS_HORIZONTAL_SCROLL: wl_pointer_axis = 1;

pub type wl_pointer_axis_source = u32;
pub const WL_POINTER_AXIS_SOURCE_WHEEL: wl_pointer_axis_source = 0;
pub const WL_POINTER_AXIS_SOURCE_FINGER: wl_pointer_axis_source = 1;
pub const WL_POINTER_AXIS_SOURCE_CONTINUOUS: wl_pointer_axis_source = 2;
pub const WL_POINTER_AXIS_SOURCE_WHEEL_TILT: wl_pointer_axis_source = 3;

pub type wl_pointer_axis_relative_direction = u32;
pub const WL_POINTER_AXIS_RELATIVE_DIRECTION_IDENTICAL: wl_pointer_axis_relative_direction = 0;
pub const WL_POINTER_AXIS_RELATIVE_DIRECTION_INVERTED: wl_pointer_axis_relative_direction = 1;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_pointer_listener {
	pub enter: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, serial: u32, surface: *mut wl_surface, surface_x: wl_fixed_t, surface_y: wl_fixed_t),

	pub leave: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, serial: u32, surface: *mut wl_surface),

	pub motion: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, time: u32, surface_x: wl_fixed_t, surface_y: wl_fixed_t),

	pub button: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, serial: u32, time: u32, button: u32, state: u32),

	pub axis: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, time: u32, axis: u32, value: wl_fixed_t),

	pub frame: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer),

	pub axis_source: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, axis_source: u32),

	pub axis_stop: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, time: u32, axis: u32),

	pub axis_discrete: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, axis: u32, discrete: i32),

	pub axis_value120: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, axis: u32, value120: i32),

	pub axis_relative_direction: unsafe extern "C" fn(data: *mut (), wl_pointer: *mut wl_pointer, axis: u32, direction: u32),
}

pub type wl_keyboard_keymap_format = u32;
pub const WL_KEYBOARD_KEYMAP_FORMAT_NO_KEYMAP: wl_keyboard_keymap_format = 0;
pub const WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1: wl_keyboard_keymap_format = 1;

pub type wl_keyboard_key_state = u32;
pub const WL_KEYBOARD_KEY_STATE_RELEASED: wl_keyboard_key_state = 0;
pub const WL_KEYBOARD_KEY_STATE_PRESSED: wl_keyboard_key_state = 1;
pub const WL_KEYBOARD_KEY_STATE_REPEATED: wl_keyboard_key_state = 2;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_keyboard_listener {
	pub keymap: unsafe extern "C" fn(data: *mut (), wl_keyboard: *mut wl_keyboard, format: u32, fd: i32, size: u32),

	pub enter: unsafe extern "C" fn(data: *mut (), wl_keyboard: *mut wl_keyboard, serial: u32, surface: *mut wl_surface, keys: *mut wl_array),

	pub leave: unsafe extern "C" fn(data: *mut (), wl_keyboard: *mut wl_keyboard, serial: u32, surface: *mut wl_surface),

	pub key: unsafe extern "C" fn(data: *mut (), wl_keyboard: *mut wl_keyboard, serial: u32, time: u32, key: u32, state: u32),

	pub modifiers: unsafe extern "C" fn(data: *mut (), wl_keyboard: *mut wl_keyboard, serial: u32, mods_depressed: u32, mods_latched: u32, mods_locked: u32, group: u32),

	pub repeat_info: unsafe extern "C" fn(data: *mut (), wl_keyboard: *mut wl_keyboard, rate: i32, delay: i32),
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_touch_listener {
	pub down: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch, serial: u32, time: u32, surface: *mut wl_surface, id: i32, x: wl_fixed_t, y: wl_fixed_t),

	pub up: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch, serial: u32, time: u32, id: i32),

	pub motion: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch, time: u32, id: i32, x: wl_fixed_t, y: wl_fixed_t),

	pub frame: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch),

	pub cancel: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch),

	pub shape: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch, id: i32, major: wl_fixed_t, minor: wl_fixed_t),

	pub orientation: unsafe extern "C" fn(data: *mut (), wl_touch: *mut wl_touch, id: i32, orientation: wl_fixed_t),
}

pub type wl_output_subpixel = u32;
pub const WL_OUTPUT_SUBPIXEL_UNKNOWN: wl_output_subpixel = 0;
pub const WL_OUTPUT_SUBPIXEL_NONE: wl_output_subpixel = 1;
pub const WL_OUTPUT_SUBPIXEL_HORIZONTAL_RGB: wl_output_subpixel = 2;
pub const WL_OUTPUT_SUBPIXEL_HORIZONTAL_BGR: wl_output_subpixel = 3;
pub const WL_OUTPUT_SUBPIXEL_VERTICAL_RGB: wl_output_subpixel = 4;
pub const WL_OUTPUT_SUBPIXEL_VERTICAL_BGR: wl_output_subpixel = 5;

pub type wl_output_transform = u32;
pub const WL_OUTPUT_TRANSFORM_NORMAL: wl_output_transform = 0;
pub const WL_OUTPUT_TRANSFORM_90: wl_output_transform = 1;
pub const WL_OUTPUT_TRANSFORM_180: wl_output_transform = 2;
pub const WL_OUTPUT_TRANSFORM_270: wl_output_transform = 3;
pub const WL_OUTPUT_TRANSFORM_FLIPPED: wl_output_transform = 4;
pub const WL_OUTPUT_TRANSFORM_FLIPPED_90: wl_output_transform = 5;
pub const WL_OUTPUT_TRANSFORM_FLIPPED_180: wl_output_transform = 6;
pub const WL_OUTPUT_TRANSFORM_FLIPPED_270: wl_output_transform = 7;

pub type wl_output_mode = u32;
pub const WL_OUTPUT_MODE_CURRENT: wl_output_mode = 1;
pub const WL_OUTPUT_MODE_PREFERRED: wl_output_mode = 2;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_output_listener {
	pub geometry:
		unsafe extern "C" fn(data: *mut (), wl_output: *mut wl_output, x: i32, y: i32, physical_width: i32, physical_height: i32, subpixel: i32, make: *const i8, model: *const i8, transform: i32),

	pub mode: unsafe extern "C" fn(data: *mut (), wl_output: *mut wl_output, flags: u32, width: i32, height: i32, refresh: i32),

	pub done: unsafe extern "C" fn(data: *mut (), wl_output: *mut wl_output),

	pub scale: unsafe extern "C" fn(data: *mut (), wl_output: *mut wl_output, factor: i32),

	pub name: unsafe extern "C" fn(data: *mut (), wl_output: *mut wl_output, name: *const i8),

	pub description: unsafe extern "C" fn(data: *mut (), wl_output: *mut wl_output, description: *const i8),
}

pub type wl_subcompositor_error = u32;
pub const WL_SUBCOMPOSITOR_ERROR_BAD_SURFACE: wl_subcompositor_error = 0;
pub const WL_SUBCOMPOSITOR_ERROR_BAD_PARENT: wl_subcompositor_error = 1;

pub type wl_subsurface_error = u32;
pub const WL_SUBSURFACE_ERROR_BAD_SURFACE: wl_subsurface_error = 0;

//
// Static inline symbols:
//

const wayland_types: [*const wl_interface; 96] = [
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_callback_interface,
	&wl_registry_interface,
	&wl_surface_interface,
	&wl_region_interface,
	&wl_buffer_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_shm_pool_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_data_source_interface,
	&wl_surface_interface,
	&wl_surface_interface,
	NULL_INTERFACE,
	&wl_data_source_interface,
	NULL_INTERFACE,
	&wl_data_offer_interface,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_data_offer_interface,
	&wl_data_offer_interface,
	&wl_data_source_interface,
	&wl_data_device_interface,
	&wl_seat_interface,
	&wl_shell_surface_interface,
	&wl_surface_interface,
	&wl_seat_interface,
	NULL_INTERFACE,
	&wl_seat_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_output_interface,
	&wl_seat_interface,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_output_interface,
	&wl_buffer_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_callback_interface,
	&wl_region_interface,
	&wl_region_interface,
	&wl_output_interface,
	&wl_output_interface,
	&wl_pointer_interface,
	&wl_keyboard_interface,
	&wl_touch_interface,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_surface_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_subsurface_interface,
	&wl_surface_interface,
	&wl_surface_interface,
	&wl_surface_interface,
	&wl_surface_interface,
	&wl_registry_interface,
];

pub const wl_display_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("sync\0"),
		signature: c_str("n\0"),
		types: &wayland_types[8],
	},
	wl_message {
		name: c_str("get_registry\0"),
		signature: c_str("n\0"),
		types: &wayland_types[9],
	},
];

pub const wl_display_events: [wl_message; 2] = [
	wl_message {
		name: c_str("error\0"),
		signature: c_str("ous\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("delete_id\0"),
		signature: c_str("u\0"),
		types: &wayland_types[0],
	},
];

pub const wl_registry_requests: [wl_message; 1] = [wl_message {
	name: c_str("bind\0"),
	signature: c_str("usun\0"),
	types: &wayland_types[0],
}];

pub const wl_registry_events: [wl_message; 2] = [
	wl_message {
		name: c_str("global\0"),
		signature: c_str("usu\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("global_remove\0"),
		signature: c_str("u\0"),
		types: &wayland_types[0],
	},
];

pub const wl_callback_events: [wl_message; 1] = [wl_message {
	name: c_str("done\0"),
	signature: c_str("u\0"),
	types: &wayland_types[0],
}];

pub const wl_compositor_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("create_surface\0"),
		signature: c_str("n\0"),
		types: &wayland_types[10],
	},
	wl_message {
		name: c_str("create_region\0"),
		signature: c_str("n\0"),
		types: &wayland_types[11],
	},
];

pub const wl_shm_pool_requests: [wl_message; 3] = [
	wl_message {
		name: c_str("create_buffer\0"),
		signature: c_str("niiiiu\0"),
		types: &wayland_types[12],
	},
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("resize\0"),
		signature: c_str("i\0"),
		types: &wayland_types[0],
	},
];

pub const wl_shm_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("create_pool\0"),
		signature: c_str("nhi\0"),
		types: &wayland_types[18],
	},
	wl_message {
		name: c_str("release\0"),
		signature: c_str("2\0"),
		types: &wayland_types[0],
	},
];

pub const wl_shm_events: [wl_message; 1] = [wl_message {
	name: c_str("format\0"),
	signature: c_str("u\0"),
	types: &wayland_types[0],
}];

pub const wl_buffer_requests: [wl_message; 1] = [wl_message {
	name: c_str("destroy\0"),
	signature: c_str("\0"),
	types: &wayland_types[0],
}];

pub const wl_buffer_events: [wl_message; 1] = [wl_message {
	name: c_str("release\0"),
	signature: c_str("\0"),
	types: &wayland_types[0],
}];

pub const wl_data_offer_requests: [wl_message; 5] = [
	wl_message {
		name: c_str("accept\0"),
		signature: c_str("u?s\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("receive\0"),
		signature: c_str("sh\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("finish\0"),
		signature: c_str("3\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_actions\0"),
		signature: c_str("3uu\0"),
		types: &wayland_types[0],
	},
];

pub const wl_data_offer_events: [wl_message; 3] = [
	wl_message {
		name: c_str("offer\0"),
		signature: c_str("s\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("source_actions\0"),
		signature: c_str("3u\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("action\0"),
		signature: c_str("3u\0"),
		types: &wayland_types[0],
	},
];

pub const wl_data_source_requests: [wl_message; 3] = [
	wl_message {
		name: c_str("offer\0"),
		signature: c_str("s\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_actions\0"),
		signature: c_str("3u\0"),
		types: &wayland_types[0],
	},
];

pub const wl_data_source_events: [wl_message; 6] = [
	wl_message {
		name: c_str("target\0"),
		signature: c_str("?s\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("send\0"),
		signature: c_str("sh\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("cancelled\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("dnd_drop_performed\0"),
		signature: c_str("3\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("dnd_finished\0"),
		signature: c_str("3\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("action\0"),
		signature: c_str("3u\0"),
		types: &wayland_types[0],
	},
];

pub const wl_data_device_requests: [wl_message; 3] = [
	wl_message {
		name: c_str("start_drag\0"),
		signature: c_str("?oo?ou\0"),
		types: &wayland_types[21],
	},
	wl_message {
		name: c_str("set_selection\0"),
		signature: c_str("?ou\0"),
		types: &wayland_types[25],
	},
	wl_message {
		name: c_str("release\0"),
		signature: c_str("2\0"),
		types: &wayland_types[0],
	},
];

pub const wl_data_device_events: [wl_message; 6] = [
	wl_message {
		name: c_str("data_offer\0"),
		signature: c_str("n\0"),
		types: &wayland_types[27],
	},
	wl_message {
		name: c_str("enter\0"),
		signature: c_str("uoff?o\0"),
		types: &wayland_types[28],
	},
	wl_message {
		name: c_str("leave\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("motion\0"),
		signature: c_str("uff\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("drop\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("selection\0"),
		signature: c_str("?o\0"),
		types: &wayland_types[33],
	},
];

pub const wl_data_device_manager_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("create_data_source\0"),
		signature: c_str("n\0"),
		types: &wayland_types[34],
	},
	wl_message {
		name: c_str("get_data_device\0"),
		signature: c_str("no\0"),
		types: &wayland_types[35],
	},
];

pub const wl_shell_requests: [wl_message; 1] = [wl_message {
	name: c_str("get_shell_surface\0"),
	signature: c_str("no\0"),
	types: &wayland_types[37],
}];

pub const wl_shell_surface_requests: [wl_message; 10] = [
	wl_message {
		name: c_str("pong\0"),
		signature: c_str("u\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("move\0"),
		signature: c_str("ou\0"),
		types: &wayland_types[39],
	},
	wl_message {
		name: c_str("resize\0"),
		signature: c_str("ouu\0"),
		types: &wayland_types[41],
	},
	wl_message {
		name: c_str("set_toplevel\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_transient\0"),
		signature: c_str("oiiu\0"),
		types: &wayland_types[44],
	},
	wl_message {
		name: c_str("set_fullscreen\0"),
		signature: c_str("uu?o\0"),
		types: &wayland_types[48],
	},
	wl_message {
		name: c_str("set_popup\0"),
		signature: c_str("ouoiiu\0"),
		types: &wayland_types[51],
	},
	wl_message {
		name: c_str("set_maximized\0"),
		signature: c_str("?o\0"),
		types: &wayland_types[57],
	},
	wl_message {
		name: c_str("set_title\0"),
		signature: c_str("s\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_class\0"),
		signature: c_str("s\0"),
		types: &wayland_types[0],
	},
];

pub const wl_shell_surface_events: [wl_message; 3] = [
	wl_message {
		name: c_str("ping\0"),
		signature: c_str("u\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("configure\0"),
		signature: c_str("uii\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("popup_done\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
];

pub const wl_surface_requests: [wl_message; 11] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("attach\0"),
		signature: c_str("?oii\0"),
		types: &wayland_types[58],
	},
	wl_message {
		name: c_str("damage\0"),
		signature: c_str("iiii\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("frame\0"),
		signature: c_str("n\0"),
		types: &wayland_types[61],
	},
	wl_message {
		name: c_str("set_opaque_region\0"),
		signature: c_str("?o\0"),
		types: &wayland_types[62],
	},
	wl_message {
		name: c_str("set_input_region\0"),
		signature: c_str("?o\0"),
		types: &wayland_types[63],
	},
	wl_message {
		name: c_str("commit\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_buffer_transform\0"),
		signature: c_str("2i\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_buffer_scale\0"),
		signature: c_str("3i\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("damage_buffer\0"),
		signature: c_str("4iiii\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("offset\0"),
		signature: c_str("5ii\0"),
		types: &wayland_types[0],
	},
];

pub const wl_surface_events: [wl_message; 4] = [
	wl_message {
		name: c_str("enter\0"),
		signature: c_str("o\0"),
		types: &wayland_types[64],
	},
	wl_message {
		name: c_str("leave\0"),
		signature: c_str("o\0"),
		types: &wayland_types[65],
	},
	wl_message {
		name: c_str("preferred_buffer_scale\0"),
		signature: c_str("6i\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("preferred_buffer_transform\0"),
		signature: c_str("6u\0"),
		types: &wayland_types[0],
	},
];

pub const wl_seat_requests: [wl_message; 4] = [
	wl_message {
		name: c_str("get_pointer\0"),
		signature: c_str("n\0"),
		types: &wayland_types[66],
	},
	wl_message {
		name: c_str("get_keyboard\0"),
		signature: c_str("n\0"),
		types: &wayland_types[67],
	},
	wl_message {
		name: c_str("get_touch\0"),
		signature: c_str("n\0"),
		types: &wayland_types[68],
	},
	wl_message {
		name: c_str("release\0"),
		signature: c_str("5\0"),
		types: &wayland_types[0],
	},
];

pub const wl_seat_events: [wl_message; 2] = [
	wl_message {
		name: c_str("capabilities\0"),
		signature: c_str("u\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("name\0"),
		signature: c_str("2s\0"),
		types: &wayland_types[0],
	},
];

pub const wl_pointer_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("set_cursor\0"),
		signature: c_str("u?oii\0"),
		types: &wayland_types[69],
	},
	wl_message {
		name: c_str("release\0"),
		signature: c_str("3\0"),
		types: &wayland_types[0],
	},
];

pub const wl_pointer_events: [wl_message; 11] = [
	wl_message {
		name: c_str("enter\0"),
		signature: c_str("uoff\0"),
		types: &wayland_types[73],
	},
	wl_message {
		name: c_str("leave\0"),
		signature: c_str("uo\0"),
		types: &wayland_types[77],
	},
	wl_message {
		name: c_str("motion\0"),
		signature: c_str("uff\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("button\0"),
		signature: c_str("uuuu\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("axis\0"),
		signature: c_str("uuf\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("frame\0"),
		signature: c_str("5\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("axis_source\0"),
		signature: c_str("5u\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("axis_stop\0"),
		signature: c_str("5uu\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("axis_discrete\0"),
		signature: c_str("5ui\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("axis_value120\0"),
		signature: c_str("8ui\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("axis_relative_direction\0"),
		signature: c_str("9uu\0"),
		types: &wayland_types[0],
	},
];

pub const wl_keyboard_requests: [wl_message; 1] = [wl_message {
	name: c_str("release\0"),
	signature: c_str("3\0"),
	types: &wayland_types[0],
}];

pub const wl_keyboard_events: [wl_message; 6] = [
	wl_message {
		name: c_str("keymap\0"),
		signature: c_str("uhu\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("enter\0"),
		signature: c_str("uoa\0"),
		types: &wayland_types[79],
	},
	wl_message {
		name: c_str("leave\0"),
		signature: c_str("uo\0"),
		types: &wayland_types[82],
	},
	wl_message {
		name: c_str("key\0"),
		signature: c_str("uuuu\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("modifiers\0"),
		signature: c_str("uuuuu\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("repeat_info\0"),
		signature: c_str("4ii\0"),
		types: &wayland_types[0],
	},
];

pub const wl_touch_requests: [wl_message; 1] = [wl_message {
	name: c_str("release\0"),
	signature: c_str("3\0"),
	types: &wayland_types[0],
}];

pub const wl_touch_events: [wl_message; 7] = [
	wl_message {
		name: c_str("down\0"),
		signature: c_str("uuoiff\0"),
		types: &wayland_types[84],
	},
	wl_message {
		name: c_str("up\0"),
		signature: c_str("uui\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("motion\0"),
		signature: c_str("uiff\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("frame\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("cancel\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("shape\0"),
		signature: c_str("6iff\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("orientation\0"),
		signature: c_str("6if\0"),
		types: &wayland_types[0],
	},
];

pub const wl_output_requests: [wl_message; 1] = [wl_message {
	name: c_str("release\0"),
	signature: c_str("3\0"),
	types: &wayland_types[0],
}];

pub const wl_output_events: [wl_message; 6] = [
	wl_message {
		name: c_str("geometry\0"),
		signature: c_str("iiiiissi\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("mode\0"),
		signature: c_str("uiii\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("done\0"),
		signature: c_str("2\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("scale\0"),
		signature: c_str("2i\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("name\0"),
		signature: c_str("4s\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("description\0"),
		signature: c_str("4s\0"),
		types: &wayland_types[0],
	},
];

pub const wl_region_requests: [wl_message; 3] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("add\0"),
		signature: c_str("iiii\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("subtract\0"),
		signature: c_str("iiii\0"),
		types: &wayland_types[0],
	},
];

pub const wl_subcompositor_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("get_subsurface\0"),
		signature: c_str("noo\0"),
		types: &wayland_types[90],
	},
];

pub const wl_subsurface_requests: [wl_message; 6] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_position\0"),
		signature: c_str("ii\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("place_above\0"),
		signature: c_str("o\0"),
		types: &wayland_types[93],
	},
	wl_message {
		name: c_str("place_below\0"),
		signature: c_str("o\0"),
		types: &wayland_types[94],
	},
	wl_message {
		name: c_str("set_sync\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("set_desync\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
];

pub const wl_fixes_requests: [wl_message; 2] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &wayland_types[0],
	},
	wl_message {
		name: c_str("destroy_registry\0"),
		signature: c_str("o\0"),
		types: &wayland_types[95],
	},
];

pub static wl_display_interface: wl_interface = wl_interface {
	name: c_str("wl_display\0"),
	version: 1,
	method_count: 2,
	methods: &wl_display_requests[0],
	event_count: 2,
	events: &wl_display_events[0],
};

pub static wl_registry_interface: wl_interface = wl_interface {
	name: c_str("wl_registry\0"),
	version: 1,
	method_count: 1,
	methods: &wl_registry_requests[0],
	event_count: 2,
	events: &wl_registry_events[0],
};

pub static wl_callback_interface: wl_interface = wl_interface {
	name: c_str("wl_callback\0"),
	version: 1,
	method_count: 0,
	methods: NULL_MESSAGE,
	event_count: 1,
	events: &wl_callback_events[0],
};

pub static wl_compositor_interface: wl_interface = wl_interface {
	name: c_str("wl_compositor\0"),
	version: 6,
	method_count: 2,
	methods: &wl_compositor_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_shm_pool_interface: wl_interface = wl_interface {
	name: c_str("wl_shm_pool\0"),
	version: 2,
	method_count: 3,
	methods: &wl_shm_pool_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_shm_interface: wl_interface = wl_interface {
	name: c_str("wl_shm\0"),
	version: 2,
	method_count: 2,
	methods: &wl_shm_requests[0],
	event_count: 1,
	events: &wl_shm_events[0],
};

pub static wl_buffer_interface: wl_interface = wl_interface {
	name: c_str("wl_buffer\0"),
	version: 1,
	method_count: 1,
	methods: &wl_buffer_requests[0],
	event_count: 1,
	events: &wl_buffer_events[0],
};

pub static wl_data_offer_interface: wl_interface = wl_interface {
	name: c_str("wl_data_offer\0"),
	version: 3,
	method_count: 5,
	methods: &wl_data_offer_requests[0],
	event_count: 3,
	events: &wl_data_offer_events[0],
};

pub static wl_data_source_interface: wl_interface = wl_interface {
	name: c_str("wl_data_source\0"),
	version: 3,
	method_count: 3,
	methods: &wl_data_source_requests[0],
	event_count: 6,
	events: &wl_data_source_events[0],
};

pub static wl_data_device_interface: wl_interface = wl_interface {
	name: c_str("wl_data_device\0"),
	version: 3,
	method_count: 3,
	methods: &wl_data_device_requests[0],
	event_count: 6,
	events: &wl_data_device_events[0],
};

pub static wl_data_device_manager_interface: wl_interface = wl_interface {
	name: c_str("wl_data_device_manager\0"),
	version: 3,
	method_count: 2,
	methods: &wl_data_device_manager_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_shell_interface: wl_interface = wl_interface {
	name: c_str("wl_shell\0"),
	version: 1,
	method_count: 1,
	methods: &wl_shell_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_shell_surface_interface: wl_interface = wl_interface {
	name: c_str("wl_shell_surface\0"),
	version: 1,
	method_count: 10,
	methods: &wl_shell_surface_requests[0],
	event_count: 3,
	events: &wl_shell_surface_events[0],
};

pub static wl_surface_interface: wl_interface = wl_interface {
	name: c_str("wl_surface\0"),
	version: 6,
	method_count: 11,
	methods: &wl_surface_requests[0],
	event_count: 4,
	events: &wl_surface_events[0],
};

pub static wl_seat_interface: wl_interface = wl_interface {
	name: c_str("wl_seat\0"),
	version: 10,
	method_count: 4,
	methods: &wl_seat_requests[0],
	event_count: 2,
	events: &wl_seat_events[0],
};

pub static wl_pointer_interface: wl_interface = wl_interface {
	name: c_str("wl_pointer\0"),
	version: 10,
	method_count: 2,
	methods: &wl_pointer_requests[0],
	event_count: 11,
	events: &wl_pointer_events[0],
};

pub static wl_keyboard_interface: wl_interface = wl_interface {
	name: c_str("wl_keyboard\0"),
	version: 10,
	method_count: 1,
	methods: &wl_keyboard_requests[0],
	event_count: 6,
	events: &wl_keyboard_events[0],
};

pub static wl_touch_interface: wl_interface = wl_interface {
	name: c_str("wl_touch\0"),
	version: 10,
	method_count: 1,
	methods: &wl_touch_requests[0],
	event_count: 7,
	events: &wl_touch_events[0],
};

pub static wl_output_interface: wl_interface = wl_interface {
	name: c_str("wl_output\0"),
	version: 4,
	method_count: 1,
	methods: &wl_output_requests[0],
	event_count: 6,
	events: &wl_output_events[0],
};

pub static wl_region_interface: wl_interface = wl_interface {
	name: c_str("wl_region\0"),
	version: 1,
	method_count: 3,
	methods: &wl_region_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_subcompositor_interface: wl_interface = wl_interface {
	name: c_str("wl_subcompositor\0"),
	version: 1,
	method_count: 2,
	methods: &wl_subcompositor_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_subsurface_interface: wl_interface = wl_interface {
	name: c_str("wl_subsurface\0"),
	version: 1,
	method_count: 6,
	methods: &wl_subsurface_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static wl_fixes_interface: wl_interface = wl_interface {
	name: c_str("wl_fixes\0"),
	version: 1,
	method_count: 2,
	methods: &wl_fixes_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub fn wl_display_get_registry(display: *mut wl_display) -> *mut wl_registry {
	let proxy = display as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_DISPLAY_GET_REGISTRY, &wl_registry_interface, version, 0, NULL_VOID) as *mut wl_registry
	}
}

pub fn wl_registry_add_listener(registry: *mut wl_registry, listener: *const wl_registry_listener, data: *mut ()) -> i32 {
	let proxy = registry as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn wl_compositor_create_surface(compositor: *mut wl_compositor) -> *mut wl_surface {
	let proxy = compositor as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_COMPOSITOR_CREATE_SURFACE, &wl_surface_interface, version, 0, NULL_VOID) as *mut wl_surface
	}
}

pub fn wl_registry_bind<T>(registry: *mut wl_registry, name: u32, interface: *const wl_interface, version: u32) -> *mut T {
	let proxy = registry as *mut wl_proxy;

	unsafe { wl_proxy_marshal_constructor(proxy, WL_REGISTRY_BIND, interface, name, (*interface).name, version, NULL_VOID) as *mut T }
}

pub fn wl_seat_get_pointer(seat: *mut wl_seat) -> *mut wl_pointer {
	let proxy = seat as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_SEAT_GET_POINTER, &wl_pointer_interface, version, 0, NULL_VOID) as *mut wl_pointer
	}
}

pub fn wl_pointer_destroy(pointer: *mut wl_pointer) {
	unsafe {
		wl_proxy_destroy(pointer as *mut wl_proxy);
	}
}

pub fn wl_seat_get_keyboard(seat: *mut wl_seat) -> *mut wl_keyboard {
	let proxy = seat as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_SEAT_GET_KEYBOARD, &wl_keyboard_interface, version, 0, NULL_VOID) as *mut wl_keyboard
	}
}

pub fn wl_keyboard_destroy(keyboard: *mut wl_keyboard) {
	unsafe {
		wl_proxy_destroy(keyboard as *mut wl_proxy);
	}
}

pub fn wl_callback_add_listener(callback: *mut wl_callback, listener: *const wl_callback_listener, data: *mut ()) -> i32 {
	let proxy = callback as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn wl_callback_destroy(callback: *mut wl_callback) {
	unsafe {
		wl_proxy_destroy(callback as *mut wl_proxy);
	}
}

pub fn wl_surface_attach(surface: *mut wl_surface, buffer: *mut wl_buffer, x: i32, y: i32) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SURFACE_ATTACH, NULL_INTERFACE, version, 0, buffer, x, y);
	}
}

pub fn wl_surface_damage_buffer(surface: *mut wl_surface, x: i32, y: i32, width: i32, height: i32) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SURFACE_DAMAGE_BUFFER, NULL_INTERFACE, version, 0, x, y, width, height);
	}
}

pub fn wl_surface_commit(surface: *mut wl_surface) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SURFACE_COMMIT, NULL_INTERFACE, version, 0);
	}
}

pub fn wl_surface_frame(surface: *mut wl_surface) -> *mut wl_callback {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_SURFACE_FRAME, &wl_callback_interface, version, 0, NULL_VOID) as *mut wl_callback
	}
}

pub fn wl_shm_create_pool(shm: *mut wl_shm, fd: i32, size: i32) -> *mut wl_shm_pool {
	let proxy = shm as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_SHM_CREATE_POOL, &wl_shm_pool_interface, version, 0, NULL_VOID, fd, size) as *mut wl_shm_pool
	}
}

pub fn wl_shm_pool_resize(shm_pool: *mut wl_shm_pool, size: i32) {
	let proxy = shm_pool as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SHM_POOL_RESIZE, NULL_INTERFACE, version, 0, size);
	}
}

pub fn wl_shm_pool_create_buffer(shm_pool: *mut wl_shm_pool, offset: i32, width: i32, height: i32, stride: i32, format: u32) -> *mut wl_buffer {
	let proxy = shm_pool as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_SHM_POOL_CREATE_BUFFER, &wl_buffer_interface, version, 0, NULL_VOID, offset, width, height, stride, format) as *mut wl_buffer
	}
}

pub fn wl_buffer_destroy(buffer: *mut wl_buffer) {
	let proxy = buffer as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_BUFFER_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}

pub fn wl_buffer_add_listener(buffer: *mut wl_buffer, listener: *const wl_buffer_listener, data: *mut ()) -> i32 {
	let proxy = buffer as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn wl_surface_destroy(surface: *mut wl_surface) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SURFACE_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}

pub fn wl_seat_destroy(seat: *mut wl_seat) {
	unsafe {
		wl_proxy_destroy(seat as *mut wl_proxy);
	}
}

pub fn wl_compositor_destroy(compositor: *mut wl_compositor) {
	unsafe {
		wl_proxy_destroy(compositor as *mut wl_proxy);
	}
}

pub fn wl_registry_destroy(registry: *mut wl_registry) {
	unsafe {
		wl_proxy_destroy(registry as *mut wl_proxy);
	}
}

pub fn wl_shm_destroy(shm: *mut wl_shm) {
	unsafe {
		wl_proxy_destroy(shm as *mut wl_proxy);
	}
}

pub fn wl_shm_pool_destroy(shm_pool: *mut wl_shm_pool) {
	let proxy = shm_pool as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SHM_POOL_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}

pub fn wl_seat_add_listener(seat: *mut wl_seat, listener: *const wl_seat_listener, data: *mut ()) -> i32 {
	let proxy = seat as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn wl_pointer_add_listener(pointer: *mut wl_pointer, listener: *const wl_pointer_listener, data: *mut ()) -> i32 {
	let proxy = pointer as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn wl_keyboard_add_listener(keyboard: *mut wl_keyboard, listener: *const wl_keyboard_listener, data: *mut ()) -> i32 {
	let proxy = keyboard as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn wl_compositor_create_region(compositor: *mut wl_compositor) -> *mut wl_region {
	let proxy = compositor as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, WL_COMPOSITOR_CREATE_REGION, &wl_region_interface, version, 0, NULL_VOID) as *mut wl_region
	}
}

pub fn wl_region_add(region: *mut wl_region, x: i32, y: i32, width: i32, height: i32) {
	let proxy = region as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_REGION_ADD, NULL_INTERFACE, version, 0, x, y, width, height);
	}
}

pub fn wl_surface_set_input_region(surface: *mut wl_surface, region: *mut wl_region) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_SURFACE_SET_INPUT_REGION, NULL_INTERFACE, version, 0, region);
	}
}

pub fn wl_region_destroy(region: *mut wl_region) {
	let proxy = region as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, WL_REGION_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}
