// NOTE: This file was first generated by wayland-scanner 1.20.0 from the
// xdg-shell XML protocol and subsequently converted with rust-bindgen. For
// the implementation of inline static Wayland functions and interfaces,
// search for "Static inline symbols".

use crate::{
	NULL_VOID, //
	c_str,
};

pub use super::{
	core::*, //
	protocol::*,
};

pub const XDG_WM_BASE_DESTROY: u32 = 0;
pub const XDG_WM_BASE_CREATE_POSITIONER: u32 = 1;
pub const XDG_WM_BASE_GET_XDG_SURFACE: u32 = 2;
pub const XDG_WM_BASE_PONG: u32 = 3;
pub const XDG_WM_BASE_PING_SINCE_VERSION: u32 = 1;
pub const XDG_WM_BASE_DESTROY_SINCE_VERSION: u32 = 1;
pub const XDG_WM_BASE_CREATE_POSITIONER_SINCE_VERSION: u32 = 1;
pub const XDG_WM_BASE_GET_XDG_SURFACE_SINCE_VERSION: u32 = 1;
pub const XDG_WM_BASE_PONG_SINCE_VERSION: u32 = 1;

pub const XDG_POSITIONER_DESTROY: u32 = 0;
pub const XDG_POSITIONER_SET_SIZE: u32 = 1;
pub const XDG_POSITIONER_SET_ANCHOR_RECT: u32 = 2;
pub const XDG_POSITIONER_SET_ANCHOR: u32 = 3;
pub const XDG_POSITIONER_SET_GRAVITY: u32 = 4;
pub const XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT: u32 = 5;
pub const XDG_POSITIONER_SET_OFFSET: u32 = 6;
pub const XDG_POSITIONER_SET_REACTIVE: u32 = 7;
pub const XDG_POSITIONER_SET_PARENT_SIZE: u32 = 8;
pub const XDG_POSITIONER_SET_PARENT_CONFIGURE: u32 = 9;
pub const XDG_POSITIONER_DESTROY_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_SIZE_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_ANCHOR_RECT_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_ANCHOR_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_GRAVITY_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_OFFSET_SINCE_VERSION: u32 = 1;
pub const XDG_POSITIONER_SET_REACTIVE_SINCE_VERSION: u32 = 3;
pub const XDG_POSITIONER_SET_PARENT_SIZE_SINCE_VERSION: u32 = 3;
pub const XDG_POSITIONER_SET_PARENT_CONFIGURE_SINCE_VERSION: u32 = 3;

pub const XDG_SURFACE_DESTROY: u32 = 0;
pub const XDG_SURFACE_GET_TOPLEVEL: u32 = 1;
pub const XDG_SURFACE_GET_POPUP: u32 = 2;
pub const XDG_SURFACE_SET_WINDOW_GEOMETRY: u32 = 3;
pub const XDG_SURFACE_ACK_CONFIGURE: u32 = 4;
pub const XDG_SURFACE_CONFIGURE_SINCE_VERSION: u32 = 1;
pub const XDG_SURFACE_DESTROY_SINCE_VERSION: u32 = 1;
pub const XDG_SURFACE_GET_TOPLEVEL_SINCE_VERSION: u32 = 1;
pub const XDG_SURFACE_GET_POPUP_SINCE_VERSION: u32 = 1;
pub const XDG_SURFACE_SET_WINDOW_GEOMETRY_SINCE_VERSION: u32 = 1;
pub const XDG_SURFACE_ACK_CONFIGURE_SINCE_VERSION: u32 = 1;

pub const XDG_TOPLEVEL_STATE_TILED_LEFT_SINCE_VERSION: u32 = 2;
pub const XDG_TOPLEVEL_STATE_TILED_RIGHT_SINCE_VERSION: u32 = 2;
pub const XDG_TOPLEVEL_STATE_TILED_TOP_SINCE_VERSION: u32 = 2;
pub const XDG_TOPLEVEL_STATE_TILED_BOTTOM_SINCE_VERSION: u32 = 2;
pub const XDG_TOPLEVEL_STATE_SUSPENDED_SINCE_VERSION: u32 = 6;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_LEFT_SINCE_VERSION: u32 = 7;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_RIGHT_SINCE_VERSION: u32 = 7;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_TOP_SINCE_VERSION: u32 = 7;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_BOTTOM_SINCE_VERSION: u32 = 7;
pub const XDG_TOPLEVEL_DESTROY: u32 = 0;
pub const XDG_TOPLEVEL_SET_PARENT: u32 = 1;
pub const XDG_TOPLEVEL_SET_TITLE: u32 = 2;
pub const XDG_TOPLEVEL_SET_APP_ID: u32 = 3;
pub const XDG_TOPLEVEL_SHOW_WINDOW_MENU: u32 = 4;
pub const XDG_TOPLEVEL_MOVE: u32 = 5;
pub const XDG_TOPLEVEL_RESIZE: u32 = 6;
pub const XDG_TOPLEVEL_SET_MAX_SIZE: u32 = 7;
pub const XDG_TOPLEVEL_SET_MIN_SIZE: u32 = 8;
pub const XDG_TOPLEVEL_SET_MAXIMIZED: u32 = 9;
pub const XDG_TOPLEVEL_UNSET_MAXIMIZED: u32 = 10;
pub const XDG_TOPLEVEL_SET_FULLSCREEN: u32 = 11;
pub const XDG_TOPLEVEL_UNSET_FULLSCREEN: u32 = 12;
pub const XDG_TOPLEVEL_SET_MINIMIZED: u32 = 13;
pub const XDG_TOPLEVEL_CONFIGURE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_CLOSE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_CONFIGURE_BOUNDS_SINCE_VERSION: u32 = 4;
pub const XDG_TOPLEVEL_WM_CAPABILITIES_SINCE_VERSION: u32 = 5;
pub const XDG_TOPLEVEL_DESTROY_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_PARENT_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_TITLE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_APP_ID_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SHOW_WINDOW_MENU_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_MOVE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_RESIZE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_MAX_SIZE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_MIN_SIZE_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_MAXIMIZED_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_UNSET_MAXIMIZED_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_FULLSCREEN_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_UNSET_FULLSCREEN_SINCE_VERSION: u32 = 1;
pub const XDG_TOPLEVEL_SET_MINIMIZED_SINCE_VERSION: u32 = 1;

pub const XDG_POPUP_DESTROY: u32 = 0;
pub const XDG_POPUP_GRAB: u32 = 1;
pub const XDG_POPUP_REPOSITION: u32 = 2;
pub const XDG_POPUP_CONFIGURE_SINCE_VERSION: u32 = 1;
pub const XDG_POPUP_POPUP_DONE_SINCE_VERSION: u32 = 1;
pub const XDG_POPUP_REPOSITIONED_SINCE_VERSION: u32 = 3;
pub const XDG_POPUP_DESTROY_SINCE_VERSION: u32 = 1;
pub const XDG_POPUP_GRAB_SINCE_VERSION: u32 = 1;
pub const XDG_POPUP_REPOSITION_SINCE_VERSION: u32 = 3;

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct xdg_popup {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct xdg_positioner {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct xdg_surface {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct xdg_toplevel {
	_unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct xdg_wm_base {
	_unused: [u8; 0],
}

pub type xdg_wm_base_error = u32;
pub const XDG_WM_BASE_ERROR_ROLE: xdg_wm_base_error = 0;
pub const XDG_WM_BASE_ERROR_DEFUNCT_SURFACES: xdg_wm_base_error = 1;
pub const XDG_WM_BASE_ERROR_NOT_THE_TOPMOST_POPUP: xdg_wm_base_error = 2;
pub const XDG_WM_BASE_ERROR_INVALID_POPUP_PARENT: xdg_wm_base_error = 3;
pub const XDG_WM_BASE_ERROR_INVALID_SURFACE_STATE: xdg_wm_base_error = 4;
pub const XDG_WM_BASE_ERROR_INVALID_POSITIONER: xdg_wm_base_error = 5;
pub const XDG_WM_BASE_ERROR_UNRESPONSIVE: xdg_wm_base_error = 6;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xdg_wm_base_listener {
	pub ping: unsafe extern "C" fn(data: *mut (), xdg_wm_base: *mut xdg_wm_base, serial: u32),
}

pub type xdg_positioner_error = u32;
pub const XDG_POSITIONER_ERROR_INVALID_INPUT: xdg_positioner_error = 0;

pub type xdg_positioner_anchor = u32;
pub const XDG_POSITIONER_ANCHOR_NONE: xdg_positioner_anchor = 0;
pub const XDG_POSITIONER_ANCHOR_TOP: xdg_positioner_anchor = 1;
pub const XDG_POSITIONER_ANCHOR_BOTTOM: xdg_positioner_anchor = 2;
pub const XDG_POSITIONER_ANCHOR_LEFT: xdg_positioner_anchor = 3;
pub const XDG_POSITIONER_ANCHOR_RIGHT: xdg_positioner_anchor = 4;
pub const XDG_POSITIONER_ANCHOR_TOP_LEFT: xdg_positioner_anchor = 5;
pub const XDG_POSITIONER_ANCHOR_BOTTOM_LEFT: xdg_positioner_anchor = 6;
pub const XDG_POSITIONER_ANCHOR_TOP_RIGHT: xdg_positioner_anchor = 7;
pub const XDG_POSITIONER_ANCHOR_BOTTOM_RIGHT: xdg_positioner_anchor = 8;

pub type xdg_positioner_gravity = u32;
pub const XDG_POSITIONER_GRAVITY_NONE: xdg_positioner_gravity = 0;
pub const XDG_POSITIONER_GRAVITY_TOP: xdg_positioner_gravity = 1;
pub const XDG_POSITIONER_GRAVITY_BOTTOM: xdg_positioner_gravity = 2;
pub const XDG_POSITIONER_GRAVITY_LEFT: xdg_positioner_gravity = 3;
pub const XDG_POSITIONER_GRAVITY_RIGHT: xdg_positioner_gravity = 4;
pub const XDG_POSITIONER_GRAVITY_TOP_LEFT: xdg_positioner_gravity = 5;
pub const XDG_POSITIONER_GRAVITY_BOTTOM_LEFT: xdg_positioner_gravity = 6;
pub const XDG_POSITIONER_GRAVITY_TOP_RIGHT: xdg_positioner_gravity = 7;
pub const XDG_POSITIONER_GRAVITY_BOTTOM_RIGHT: xdg_positioner_gravity = 8;

pub type xdg_positioner_constraint_adjustment = u32;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_NONE: xdg_positioner_constraint_adjustment = 0;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_X: xdg_positioner_constraint_adjustment = 1;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_Y: xdg_positioner_constraint_adjustment = 2;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_X: xdg_positioner_constraint_adjustment = 4;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_Y: xdg_positioner_constraint_adjustment = 8;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_X: xdg_positioner_constraint_adjustment = 16;
pub const XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_Y: xdg_positioner_constraint_adjustment = 32;

pub type xdg_surface_error = u32;
pub const XDG_SURFACE_ERROR_NOT_CONSTRUCTED: xdg_surface_error = 1;
pub const XDG_SURFACE_ERROR_ALREADY_CONSTRUCTED: xdg_surface_error = 2;
pub const XDG_SURFACE_ERROR_UNCONFIGURED_BUFFER: xdg_surface_error = 3;
pub const XDG_SURFACE_ERROR_INVALID_SERIAL: xdg_surface_error = 4;
pub const XDG_SURFACE_ERROR_INVALID_SIZE: xdg_surface_error = 5;
pub const XDG_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT: xdg_surface_error = 6;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xdg_surface_listener {
	pub configure: unsafe extern "C" fn(data: *mut (), xdg_surface: *mut xdg_surface, serial: u32),
}

pub type xdg_toplevel_error = u32;
pub const XDG_TOPLEVEL_ERROR_INVALID_RESIZE_EDGE: xdg_toplevel_error = 0;
pub const XDG_TOPLEVEL_ERROR_INVALID_PARENT: xdg_toplevel_error = 1;
pub const XDG_TOPLEVEL_ERROR_INVALID_SIZE: xdg_toplevel_error = 2;

pub type xdg_toplevel_resize_edge = u32;
pub const XDG_TOPLEVEL_RESIZE_EDGE_NONE: xdg_toplevel_resize_edge = 0;
pub const XDG_TOPLEVEL_RESIZE_EDGE_TOP: xdg_toplevel_resize_edge = 1;
pub const XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM: xdg_toplevel_resize_edge = 2;
pub const XDG_TOPLEVEL_RESIZE_EDGE_LEFT: xdg_toplevel_resize_edge = 4;
pub const XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT: xdg_toplevel_resize_edge = 5;
pub const XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT: xdg_toplevel_resize_edge = 6;
pub const XDG_TOPLEVEL_RESIZE_EDGE_RIGHT: xdg_toplevel_resize_edge = 8;
pub const XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT: xdg_toplevel_resize_edge = 9;
pub const XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT: xdg_toplevel_resize_edge = 10;

pub type xdg_toplevel_state = u32;
pub const XDG_TOPLEVEL_STATE_MAXIMIZED: xdg_toplevel_state = 1;
pub const XDG_TOPLEVEL_STATE_FULLSCREEN: xdg_toplevel_state = 2;
pub const XDG_TOPLEVEL_STATE_RESIZING: xdg_toplevel_state = 3;
pub const XDG_TOPLEVEL_STATE_ACTIVATED: xdg_toplevel_state = 4;
pub const XDG_TOPLEVEL_STATE_TILED_LEFT: xdg_toplevel_state = 5;
pub const XDG_TOPLEVEL_STATE_TILED_RIGHT: xdg_toplevel_state = 6;
pub const XDG_TOPLEVEL_STATE_TILED_TOP: xdg_toplevel_state = 7;
pub const XDG_TOPLEVEL_STATE_TILED_BOTTOM: xdg_toplevel_state = 8;
pub const XDG_TOPLEVEL_STATE_SUSPENDED: xdg_toplevel_state = 9;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_LEFT: xdg_toplevel_state = 10;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_RIGHT: xdg_toplevel_state = 11;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_TOP: xdg_toplevel_state = 12;
pub const XDG_TOPLEVEL_STATE_CONSTRAINED_BOTTOM: xdg_toplevel_state = 13;

pub type xdg_toplevel_wm_capabilities = u32;
pub const XDG_TOPLEVEL_WM_CAPABILITIES_WINDOW_MENU: xdg_toplevel_wm_capabilities = 1;
pub const XDG_TOPLEVEL_WM_CAPABILITIES_MAXIMIZE: xdg_toplevel_wm_capabilities = 2;
pub const XDG_TOPLEVEL_WM_CAPABILITIES_FULLSCREEN: xdg_toplevel_wm_capabilities = 3;
pub const XDG_TOPLEVEL_WM_CAPABILITIES_MINIMIZE: xdg_toplevel_wm_capabilities = 4;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xdg_toplevel_listener {
	pub configure: unsafe extern "C" fn(data: *mut (), xdg_toplevel: *mut xdg_toplevel, width: i32, height: i32, states: *mut wl_array),

	pub close: unsafe extern "C" fn(data: *mut (), xdg_toplevel: *mut xdg_toplevel),

	pub configure_bounds: unsafe extern "C" fn(data: *mut (), xdg_toplevel: *mut xdg_toplevel, width: i32, height: i32),

	pub wm_capabilities: unsafe extern "C" fn(data: *mut (), xdg_toplevel: *mut xdg_toplevel, capabilities: *mut wl_array),
}

pub type xdg_popup_error = u32;
pub const XDG_POPUP_ERROR_INVALID_GRAB: xdg_popup_error = 0;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xdg_popup_listener {
	pub configure: unsafe extern "C" fn(data: *mut (), xdg_popup: *mut xdg_popup, x: i32, y: i32, width: i32, height: i32),

	pub popup_done: unsafe extern "C" fn(data: *mut (), xdg_popup: *mut xdg_popup),

	pub repositioned: unsafe extern "C" fn(data: *mut (), xdg_popup: *mut xdg_popup, token: u32),
}

//
// Static inline symbols:
//

const xdg_shell_types: [*const wl_interface; 26] = [
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&xdg_positioner_interface,
	&xdg_surface_interface,
	&wl_surface_interface,
	&xdg_toplevel_interface,
	&xdg_popup_interface,
	&xdg_surface_interface,
	&xdg_positioner_interface,
	&xdg_toplevel_interface,
	&wl_seat_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_seat_interface,
	NULL_INTERFACE,
	&wl_seat_interface,
	NULL_INTERFACE,
	NULL_INTERFACE,
	&wl_output_interface,
	&wl_seat_interface,
	NULL_INTERFACE,
	&xdg_positioner_interface,
	NULL_INTERFACE,
];

pub const xdg_wm_base_requests: [wl_message; 4] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("create_positioner\0"),
		signature: c_str("n\0"),
		types: &xdg_shell_types[4],
	},
	wl_message {
		name: c_str("get_xdg_surface\0"),
		signature: c_str("no\0"),
		types: &xdg_shell_types[5],
	},
	wl_message {
		name: c_str("pong\0"),
		signature: c_str("u\0"),
		types: &xdg_shell_types[0],
	},
];

pub const xdg_wm_base_events: [wl_message; 1] = [wl_message {
	name: c_str("ping\0"),
	signature: c_str("u\0"),
	types: &xdg_shell_types[0],
}];

pub const xdg_positioner_requests: [wl_message; 10] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_size\0"),
		signature: c_str("ii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_anchor_rect\0"),
		signature: c_str("iiii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_anchor\0"),
		signature: c_str("u\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_gravity\0"),
		signature: c_str("u\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_constraint_adjustment\0"),
		signature: c_str("u\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_offset\0"),
		signature: c_str("ii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_reactive\0"),
		signature: c_str("3\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_parent_size\0"),
		signature: c_str("3ii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_parent_configure\0"),
		signature: c_str("3u\0"),
		types: &xdg_shell_types[0],
	},
];

pub const xdg_surface_requests: [wl_message; 5] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("get_toplevel\0"),
		signature: c_str("n\0"),
		types: &xdg_shell_types[7],
	},
	wl_message {
		name: c_str("get_popup\0"),
		signature: c_str("n?oo\0"),
		types: &xdg_shell_types[8],
	},
	wl_message {
		name: c_str("set_window_geometry\0"),
		signature: c_str("iiii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("ack_configure\0"),
		signature: c_str("u\0"),
		types: &xdg_shell_types[0],
	},
];

pub const xdg_surface_events: [wl_message; 1] = [wl_message {
	name: c_str("configure\0"),
	signature: c_str("u\0"),
	types: &xdg_shell_types[0],
}];

pub const xdg_toplevel_requests: [wl_message; 14] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_parent\0"),
		signature: c_str("?o\0"),
		types: &xdg_shell_types[11],
	},
	wl_message {
		name: c_str("set_title\0"),
		signature: c_str("s\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_app_id\0"),
		signature: c_str("s\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("show_window_menu\0"),
		signature: c_str("ouii\0"),
		types: &xdg_shell_types[12],
	},
	wl_message {
		name: c_str("move\0"),
		signature: c_str("ou\0"),
		types: &xdg_shell_types[16],
	},
	wl_message {
		name: c_str("resize\0"),
		signature: c_str("ouu\0"),
		types: &xdg_shell_types[18],
	},
	wl_message {
		name: c_str("set_max_size\0"),
		signature: c_str("ii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_min_size\0"),
		signature: c_str("ii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_maximized\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("unset_maximized\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_fullscreen\0"),
		signature: c_str("?o\0"),
		types: &xdg_shell_types[21],
	},
	wl_message {
		name: c_str("unset_fullscreen\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("set_minimized\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
];

pub const xdg_toplevel_events: [wl_message; 4] = [
	wl_message {
		name: c_str("configure\0"),
		signature: c_str("iia\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("close\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("configure_bounds\0"),
		signature: c_str("4ii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("wm_capabilities\0"),
		signature: c_str("5a\0"),
		types: &xdg_shell_types[0],
	},
];

pub const xdg_popup_requests: [wl_message; 3] = [
	wl_message {
		name: c_str("destroy\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("grab\0"),
		signature: c_str("ou\0"),
		types: &xdg_shell_types[22],
	},
	wl_message {
		name: c_str("reposition\0"),
		signature: c_str("3ou\0"),
		types: &xdg_shell_types[24],
	},
];

pub const xdg_popup_events: [wl_message; 3] = [
	wl_message {
		name: c_str("configure\0"),
		signature: c_str("iiii\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("popup_done\0"),
		signature: c_str("\0"),
		types: &xdg_shell_types[0],
	},
	wl_message {
		name: c_str("repositioned\0"),
		signature: c_str("3u\0"),
		types: &xdg_shell_types[0],
	},
];

pub static xdg_wm_base_interface: wl_interface = wl_interface {
	name: c_str("xdg_wm_base\0"),
	version: 7,
	method_count: 4,
	methods: &xdg_wm_base_requests[0],
	event_count: 1,
	events: &xdg_wm_base_events[0],
};

pub static xdg_positioner_interface: wl_interface = wl_interface {
	name: c_str("xdg_positioner\0"),
	version: 7,
	method_count: 10,
	methods: &xdg_positioner_requests[0],
	event_count: 0,
	events: NULL_MESSAGE,
};

pub static xdg_surface_interface: wl_interface = wl_interface {
	name: c_str("xdg_surface\0"),
	version: 7,
	method_count: 5,
	methods: &xdg_surface_requests[0],
	event_count: 1,
	events: &xdg_surface_events[0],
};

pub static xdg_toplevel_interface: wl_interface = wl_interface {
	name: c_str("xdg_toplevel\0"),
	version: 7,
	method_count: 14,
	methods: &xdg_toplevel_requests[0],
	event_count: 4,
	events: &xdg_toplevel_events[0],
};

pub static xdg_popup_interface: wl_interface = wl_interface {
	name: c_str("xdg_popup\0"),
	version: 7,
	method_count: 3,
	methods: &xdg_popup_requests[0],
	event_count: 3,
	events: &xdg_popup_events[0],
};

pub fn xdg_wm_base_get_xdg_surface(wm_base: *mut xdg_wm_base, surface: *mut wl_surface) -> *mut xdg_surface {
	let proxy = wm_base as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, XDG_WM_BASE_GET_XDG_SURFACE, &xdg_surface_interface, version, 0, NULL_VOID, surface) as *mut xdg_surface
	}
}

pub fn xdg_surface_get_toplevel(surface: *mut xdg_surface) -> *mut xdg_toplevel {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		wl_proxy_marshal_flags(proxy, XDG_SURFACE_GET_TOPLEVEL, &xdg_toplevel_interface, version, 0, NULL_VOID) as *mut xdg_toplevel
	}
}

pub fn xdg_toplevel_set_title(toplevel: *mut xdg_toplevel, title: *const i8) {
	let proxy = toplevel as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_TOPLEVEL_SET_TITLE, NULL_INTERFACE, version, 0, title);
	}
}

pub fn xdg_wm_base_pong(wm_base: *mut xdg_wm_base, serial: u32) {
	let proxy = wm_base as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_WM_BASE_PONG, NULL_INTERFACE, version, 0, serial);
	}
}

pub fn xdg_wm_base_add_listener(wm_base: *mut xdg_wm_base, listener: *const xdg_wm_base_listener, data: *mut ()) -> i32 {
	let proxy = wm_base as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn xdg_surface_ack_configure(surface: *mut xdg_surface, serial: u32) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_SURFACE_ACK_CONFIGURE, NULL_INTERFACE, version, 0, serial);
	}
}

pub fn xdg_surface_add_listener(surface: *mut xdg_surface, listener: *const xdg_surface_listener, data: *mut ()) -> i32 {
	let proxy = surface as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn xdg_toplevel_add_listener(toplevel: *mut xdg_toplevel, listener: *const xdg_toplevel_listener, data: *mut ()) -> i32 {
	let proxy = toplevel as *mut wl_proxy;

	let listener = (listener as *const _) as *const *const unsafe extern "C" fn();

	unsafe { wl_proxy_add_listener(proxy, listener, data) }
}

pub fn xdg_toplevel_destroy(toplevel: *mut xdg_toplevel) {
	let proxy = toplevel as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_TOPLEVEL_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}

pub fn xdg_surface_destroy(surface: *mut xdg_surface) {
	let proxy = surface as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_SURFACE_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}

pub fn xdg_wm_base_destroy(wm_base: *mut xdg_wm_base) {
	let proxy = wm_base as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_WM_BASE_DESTROY, NULL_INTERFACE, version, WL_MARSHAL_FLAG_DESTROY);
	}
}

pub fn xdg_toplevel_set_min_size(toplevel: *mut xdg_toplevel, width: i32, height: i32) {
	let proxy = toplevel as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_TOPLEVEL_SET_MIN_SIZE, NULL_INTERFACE, version, 0, width, height);
	}
}

pub fn xdg_toplevel_set_max_size(toplevel: *mut xdg_toplevel, width: i32, height: i32) {
	let proxy = toplevel as *mut wl_proxy;

	unsafe {
		let version = wl_proxy_get_version(proxy);

		let _ = wl_proxy_marshal_flags(proxy, XDG_TOPLEVEL_SET_MAX_SIZE, NULL_INTERFACE, version, 0, width, height);
	}
}
